/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import java.io.DataInputStream;
import java.io.IOException;
import java.math.BigInteger;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

public class gui_rsa extends javax.swing.JFrame {

    private BigInteger p;
    private BigInteger q;
    private BigInteger n;
    private BigInteger phi;
    private BigInteger e;
    private BigInteger d;
    private int maxLength = 1024;
    private Random r;
    byte[] cipher;
    
    private void limpiar(){
       txtClaveE.setText("");
       txtClave1D.setText("");
       txtClave2N.setText("");
       textMesnaje.setText("");
       
       e = null;
       n = null;
       d = null;
       cipher = null;
    }
    
    private void generacionLlaves(){
        
        //recreacion de las operaciones RSA
        r = new Random();
        p = BigInteger.probablePrime(maxLength, r);
        q = BigInteger.probablePrime(maxLength, r);
        n = p.multiply(q);
        phi = p.subtract(BigInteger.ONE).multiply(  q.subtract(BigInteger.ONE));
        e = BigInteger.probablePrime(maxLength/2, r);
        
        while(phi.gcd(e).compareTo(BigInteger.ONE) > 0 && e.compareTo(phi) < 0){
            e.add(BigInteger.ONE);
        }
        
        d = e.modInverse(phi);
        
        //imprecion en las cajas de texto
       txtClaveE.setText( e.toString() );
       txtClave1D.setText( d.toString());
       txtClave2N.setText( n.toString() ) ;
       
    }//generacionLlaves

    private void cifradoMensaje(){
        
        String mensaje = "", clave1 = "", clave2 = "";
        String _bytesString;
        
        mensaje = textMesnaje.getText();
        clave1 = txtClaveE.getText();
        clave2 = txtClave2N.getText();
        
        if( !clave1.equals("") && !clave2.equals("") ){
            
            if( !mensaje.equals("") ){
                cipher = encriptarmensaje(mensaje.getBytes());
                textMesnaje.setText(cipher.toString());
                mensaje(" Se ha cifrado el mensaje ", "", 1);
            }else{
                mensaje("Coloca tu mensaje a cifrar", "advertencia", 2);
            }
            
        }else{
            mensaje("Comprueba que los campos esten llenos", "Advertencia", 2);
        }
        
        
    }//cifradoMensaje
    
    
    private void desifrar(){
        
        String mensaje = "", clave1 = "", clave2 = "";
        String _bytesString;

        
        DataInputStream input = new DataInputStream(System.in);
        
        mensaje = textMesnaje.getText();
        clave1 = txtClave1D.getText();
        clave2 = txtClave2N.getText();
        
        if( !clave1.equals("") && !clave2.equals("") ){

            if( !mensaje.equals("") ){
                System.out.println(cipher);
                byte[] des = desemcriptarMensaje(cipher);
                textMesnaje.setText(new String(des));
                
                mensaje(" Se a decifrado el mensaje ", "", 1);
            }else{
                mensaje("Coloca tu mensaje a cifrar", "Advertencia", 2);
            }
            
        }else{
            mensaje("Comprueba que los campos esten llenos", "Advertencia", 2);
        }
    }//desifrar
    
    
    
    // Enciptar mensaje
    private byte[] encriptarmensaje(byte[] messaje)
    {
        return (new BigInteger(messaje)).modPow(e, n).toByteArray();
    }//encriptarmensaje
 
    // Decrypting the message
    private byte[] desemcriptarMensaje(byte[] messaje)
    {
        return (new BigInteger(messaje)).modPow(d, n).toByteArray();
    }//desemcriptarMensaje
    
    //ventana de daialogo para la muestra de mensajes
    private void mensaje(String _mensaje, String titulo, int tipo){
        JOptionPane.showMessageDialog(null, _mensaje, titulo, tipo);
    }//mensaje
    
    /**
     * Creates new form gui_rea
     */
    public gui_rsa() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCifrar = new javax.swing.JButton();
        btnDesifrado = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtClaveE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textMesnaje = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtClave1D = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtClave2N = new javax.swing.JTextField();
        btnGeneralClave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RSA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        panelPrincipal.setToolTipText("");

        jLabel1.setText("E");

        btnCifrar.setText("cifrado");
        btnCifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCifrarActionPerformed(evt);
            }
        });

        btnDesifrado.setText("Desifrado");
        btnDesifrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesifradoActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtClaveE.setEditable(false);
        txtClaveE.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Mensaje");

        textMesnaje.setColumns(20);
        textMesnaje.setLineWrap(true);
        textMesnaje.setRows(5);
        jScrollPane1.setViewportView(textMesnaje);

        jLabel3.setText("D");

        txtClave1D.setEditable(false);
        txtClave1D.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("N");

        txtClave2N.setEditable(false);
        txtClave2N.setBackground(new java.awt.Color(255, 255, 255));

        btnGeneralClave.setText("GenerarClave");
        btnGeneralClave.setFocusCycleRoot(true);
        btnGeneralClave.setFocusTraversalPolicyProvider(true);
        btnGeneralClave.setSelected(true);
        btnGeneralClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralClaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtClave2N, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClave1D, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClaveE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnCifrar)
                .addGap(67, 67, 67)
                .addComponent(btnGeneralClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnDesifrado)
                .addGap(54, 54, 54))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClaveE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClave1D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClave2N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCifrar)
                    .addComponent(btnDesifrado)
                    .addComponent(btnGeneralClave))
                .addGap(28, 28, 28)
                .addComponent(btnLimpiar)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCifrarActionPerformed
        // TODO add your handling code here:
        
        cifradoMensaje();
        
    }//GEN-LAST:event_btnCifrarActionPerformed

    private void btnGeneralClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralClaveActionPerformed
        // TODO add your handling code here:
        generacionLlaves();
    }//GEN-LAST:event_btnGeneralClaveActionPerformed

    private void btnDesifradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesifradoActionPerformed
        // TODO add your handling code here:
        desifrar();
    }//GEN-LAST:event_btnDesifradoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui_rsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui_rsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui_rsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui_rsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui_rsa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCifrar;
    private javax.swing.JButton btnDesifrado;
    private javax.swing.JButton btnGeneralClave;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextArea textMesnaje;
    private javax.swing.JTextField txtClave1D;
    private javax.swing.JTextField txtClave2N;
    private javax.swing.JTextField txtClaveE;
    // End of variables declaration//GEN-END:variables
}
